// category
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'

// post
export const SET_POSTS = 'SET_POSTS'
export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CURRENT_POST = 'SET_CURRENT_POST'
export const UPDATE_POST_IN_LIST = 'UPDATE_POST_IN_LIST'
export const UPDATE_MODAL_POST = 'UPDATE_MODAL_POST'
export const OPEN_POST_MODAL = 'OPEN_POST_MODAL'
export const CLOSE_POST_MODAL = 'CLOSE_POST_MODAL'

// comment
export const RESET_COMMENT_LIST = 'RESET_COMMENT_LIST'
export const APPEND_COMMENTS = 'APPEND_COMMENTS'
export const SET_CURRENT_COMMENTS = 'SET_CURRENT_COMMENTS'
export const UPDATE_COMMENT_IN_LIST = 'UPDATE_COMMENT_IN_LIST'
export const OPEN_COMMENT_MODAL = 'OPEN_COMMENT_MODAL'
export const CLOSE_COMMENT_MODAL = 'CLOSE_COMMENT_MODAL'
export const UPDATE_MODAL_COMMENT = 'UPDATE_MODAL_COMMENT'
